# Generated by Django 4.1.13 on 2025-04-05 10:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_header_products_discount_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sale Rate'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='product_qnty',
            field=models.PositiveIntegerField(default=0, verbose_name='Product Qnty'),
        ),
        migrations.AlterField(
            model_name='header',
            name='order_date',
            field=models.DateField(verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='header',
            name='order_time',
            field=models.TimeField(verbose_name='Order Time'),
        ),
    ]
