# Generated by Django 4.1.13 on 2025-04-05 10:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_products_sale_rate_alter_detail_product_qnty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount Rate'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sale Rate'),
        ),
    ]
