# Generated by Django 4.1.13 on 2025-04-09 06:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_remove_products_discount_rate_remove_products_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='header',
            name='total_sale_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Sale Amount'),
        ),
    ]
