# Generated by Django 4.1.13 on 2025-04-17 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='product_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='detail/'),
            preserve_default=False,
        ),
    ]
